"""
D2 — ML Confidence Distribution Check.

Read-only diagnostic. Compares live ML confidence values (parsed from container
logs) against the training-time distribution (regenerated by replaying the
training pipeline on freshly-fetched 90d/4h OHLCV).

Per user modification #2: if live N < 500, skip KS test and report mean±std
comparison + percentile + INCONCLUSIVE verdict.

Outputs:
  /app/data/diagnostics/d2_live_conf.csv      — parsed live values
  /app/data/diagnostics/d2_train_conf.csv     — regenerated training-time confidences
  /app/data/diagnostics/d2_summary.json       — mean/std/percentile + verdict

Run inside aaats-paper-crypto:
    docker exec aaats-paper-crypto python /app/diagnostics/d2_ml_dist.py
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

import ccxt
import numpy as np
import pandas as pd

sys.path.insert(0, "/app")

OUT = Path("/app/data/diagnostics")
OUT.mkdir(parents=True, exist_ok=True)

LIVE_LOG_RE = re.compile(r"ML gate: conf=([0-9.]+)\s*->\s*SKIP\s+(\w+)")

SYMBOLS = ["BTC/USDT", "ETH/USDT", "SOL/USDT", "LINK/USDT", "DOT/USDT", "AVAX/USDT"]
N_BARS_4H = 540


def parse_live_conf_from_logs() -> pd.DataFrame:
    """
    Best-effort parse of ML confidence values from the running container's logs.
    Reads via 'docker logs' — but this script *runs inside* the container so
    we read /proc/1/fd/1 isn't reliable. Instead parse the container's stderr/stdout
    file shared via host mount, OR fall back to the subprocess approach if available.

    In practice, when run via `docker exec`, the container can't read its own
    logs from inside. So we mount-of-last-resort: write a tiny stub that the
    host wrapper script will populate, OR rely on a pre-staged log file.

    The host wrapper provides logs via /tmp/d2_live_logs.txt (mounted/copied).
    """
    candidates = [
        Path("/tmp/d2_live_logs.txt"),
        Path("/app/data/diagnostics/_d2_live_logs.txt"),
    ]
    for p in candidates:
        if p.exists():
            text = p.read_text(errors="replace")
            break
    else:
        return pd.DataFrame(columns=["conf", "signal"])

    matches = LIVE_LOG_RE.findall(text)
    rows = [{"conf": float(c), "signal": s} for c, s in matches]
    return pd.DataFrame(rows)


def fetch_ohlcv_4h(symbol: str, n: int) -> pd.DataFrame:
    ex = ccxt.binance({"enableRateLimit": True})
    rows = ex.fetch_ohlcv(symbol, "4h", limit=n)
    df = pd.DataFrame(rows, columns=["ts_ms", "open", "high", "low", "close", "volume"])
    df["ts"] = pd.to_datetime(df["ts_ms"], unit="ms", utc=True)
    return df.set_index("ts").drop(columns="ts_ms")


def regenerate_training_conf() -> pd.DataFrame:
    """
    Replay the production scoring path on 90d/4h to approximate the
    training-time confidence distribution.

    Uses `ml.train_from_history.load_saved_models()` — the same read-only
    loader live_paper_runner uses in production. Verified read-only:
    no save/dump/write-mode open in load_saved_models, only XGBoost
    load_model + pickle.load.
    """
    from ml.train_from_history import load_saved_models
    from ml.xgboost_ensemble import score_signal

    ensemble = load_saved_models(max_age_days=7)
    if ensemble is None:
        print("  [warn] load_saved_models returned None — model stale or missing")
        return pd.DataFrame(columns=["ts", "symbol", "conf"])

    from diagnostics.d1_voter_replay import add_features

    rows: list[dict] = []
    for sym in SYMBOLS:
        try:
            print(f"  fetching {sym} ...", end=" ", flush=True)
            raw = fetch_ohlcv_4h(sym, N_BARS_4H)
            feat = add_features(raw).dropna()
            print(f"{len(feat)} bars")
            for i in range(50, len(feat)):
                row = feat.iloc[i]
                try:
                    conf = score_signal("crypto", row, ensemble)
                    rows.append({
                        "ts": feat.index[i].isoformat(),
                        "symbol": sym,
                        "conf": float(conf),
                    })
                except Exception:
                    pass
        except Exception as e:
            print(f"  FAIL {sym}: {e}")
    return pd.DataFrame(rows)


def main() -> int:
    print("== D2 ML confidence distribution ==")

    # --- Live (parsed from logs) ---
    live = parse_live_conf_from_logs()
    print(f"Live conf records: {len(live)}")
    live.to_csv(OUT / "d2_live_conf.csv", index=False)

    # --- Training-time (regenerated) ---
    print("Regenerating training-time confidence on 90d/4h ...")
    train = regenerate_training_conf()
    print(f"Training-time conf records: {len(train)}")
    train.to_csv(OUT / "d2_train_conf.csv", index=False)

    # --- Stats ---
    n_live = len(live)
    if n_live == 0 or len(train) == 0:
        verdict = "INCONCLUSIVE"
        notes = ["No live samples or empty training distribution — cannot compare."]
    elif n_live < 500:
        verdict = "INCONCLUSIVE"
        notes = [
            f"Live N={n_live} < 500 — KS test underpowered, skipped per protocol.",
            "Reporting mean±std + percentile location instead.",
            "Recommend: extend Docker log retention (json-driver max-size) and re-run in 2 weeks.",
        ]
    else:
        verdict = None  # populated below
        notes = []

    train_arr = train["conf"].astype(float).to_numpy()
    live_arr = live["conf"].astype(float).to_numpy() if n_live else np.array([])

    summary = {
        "diagnostic": "D2_ml_dist",
        "verdict": verdict or "PENDING",
        "n_live": int(n_live),
        "n_train_replay": int(len(train)),
        "training_meta_recorded_samples": None,
        "live_mean":  float(np.mean(live_arr))   if n_live else None,
        "live_std":   float(np.std(live_arr))    if n_live else None,
        "train_mean": float(np.mean(train_arr))  if len(train_arr) else None,
        "train_std":  float(np.std(train_arr))   if len(train_arr) else None,
        "live_mean_percentile_in_training": (
            float(np.mean(train_arr <= np.mean(live_arr)) * 100.0)
            if (n_live and len(train_arr)) else None
        ),
        "ks_test_run": False,
        "notes": notes,
    }

    # Recorded training set size (from training_meta.json — authoritative)
    meta_p = Path("/app/data/ml/training_meta.json")
    if meta_p.exists():
        meta = json.loads(meta_p.read_text())
        summary["training_meta_recorded_samples"] = meta.get("samples_crypto")
        summary["training_meta_val_acc"]          = meta.get("val_acc_crypto")
        summary["training_meta_trained_at"]       = meta.get("trained_at")

    if verdict is None:
        # only reached when N >= 500; would run KS test here but protocol says N<500 path
        # is the only currently-relevant branch
        summary["verdict"] = "INCONCLUSIVE"

    (OUT / "d2_summary.json").write_text(json.dumps(summary, indent=2))
    print(f"\n[OK] wrote {OUT}/d2_summary.json")
    print(f"VERDICT: {summary['verdict']}")
    print(f"  live  : N={n_live}  mean={summary['live_mean']}  std={summary['live_std']}")
    print(f"  train : N={summary['n_train_replay']}  mean={summary['train_mean']}  std={summary['train_std']}")
    if summary['live_mean_percentile_in_training'] is not None:
        print(f"  live mean falls at training-distribution percentile: {summary['live_mean_percentile_in_training']:.1f}%")
    return 0


if __name__ == "__main__":
    sys.exit(main())
